apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: enforce-strict-mtls
  annotations:
    policies.kyverno.io/title: Enforce Istio Strict mTLS
    policies.kyverno.io/category: Security
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: PeerAuthentication
    kyverno.io/kyverno-version: 1.8.0
    policies.kyverno.io/minversion: 1.6.0
    kyverno.io/kubernetes-version: "1.24"
    policies.kyverno.io/description: >- 
      Strict mTLS requires that mutual TLS be enabled across the entire service mesh, which
      can be set using a PeerAuthentication resource on a per-Namespace basis. This policy
      automatically creates and enforces strict mTLS for namespaces starting with 'at'.
spec:
  validationFailureAction: Enforce
  background: true
  rules:
  - name: create-mtls-policy
    match:
      any:
      - resources:
          kinds:
          - Namespace
          name: "at*"
    generate:
      apiVersion: security.istio.io/v1beta1
      kind: PeerAuthentication
      name: default
      namespace: "{{request.object.metadata.name}}"
      synchronize: true
      data:
        spec:
          mtls:
            mode: STRICT
  - name: validate-mtls
    match:
      any:
      - resources:
          kinds:
          - PeerAuthentication
          namespaceSelector:
            matchExpressions:
            - key: kubernetes.io/metadata.name
              operator: Matches
              values: ["at*"]
    validate:
      message: "PeerAuthentication resources in 'at' namespaces must use STRICT mode"
      pattern:
        spec:
          mtls:
            mode: "STRICT" 