apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kyverno-admission-controller-vpa
rules:
- apiGroups:
  - "autoscaling.k8s.io"
  resources:
  - verticalpodautoscalers
  - verticalpodautoscalercheckpoints
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kyverno-admission-controller-vpa-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kyverno-admission-controller-vpa
subjects:
- kind: ServiceAccount
  name: kyverno-admission-controller
  namespace: kyverno