apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: verticalpodautoscalers.autoscaling.k8s.io
spec:
  group: autoscaling.k8s.io
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              targetRef:
                type: object
                properties:
                  apiVersion:
                    type: string
                  kind:
                    type: string
                  name:
                    type: string
                required:
                - apiVersion
                - kind
                - name
              updatePolicy:
                type: object
                properties:
                  updateMode:
                    type: string
                    enum:
                    - "Off"
                    - "Initial"
                    - "Recreation"
                    - "Auto"
              resourcePolicy:
                type: object
                properties:
                  containerPolicies:
                    type: array
                    items:
                      type: object
                      properties:
                        containerName:
                          type: string
                        mode:
                          type: string
                          enum:
                          - "Auto"
                          - "Off"
                        minAllowed:
                          type: object
                          additionalProperties:
                            type: string
                        maxAllowed:
                          type: object
                          additionalProperties:
                            type: string
                        controlledResources:
                          type: array
                          items:
                            type: string
                        controlledValues:
                          type: string
                          enum:
                          - "RequestsAndLimits"
                          - "RequestsOnly"
            required:
            - targetRef
          status:
            type: object
            properties:
              lastUpdateTime:
                type: string
                format: date-time
              recommendation:
                type: object
                properties:
                  containerRecommendations:
                    type: array
                    items:
                      type: object
                      properties:
                        containerName:
                          type: string
                        target:
                          type: object
                          additionalProperties:
                            type: string
                        lowerBound:
                          type: object
                          additionalProperties:
                            type: string
                        upperBound:
                          type: object
                          additionalProperties:
                            type: string
                        uncappedTarget:
                          type: object
                          additionalProperties:
                            type: string
              conditions:
                type: array
                items:
                  type: object
                  properties:
                    type:
                      type: string
                    status:
                      type: string
                    lastTransitionTime:
                      type: string
                      format: date-time
                    reason:
                      type: string
                    message:
                      type: string
  scope: Namespaced
  names:
    plural: verticalpodautoscalers
    singular: verticalpodautoscaler
    kind: VerticalPodAutoscaler
    shortNames:
    - vpa
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: verticalpodautoscalercheckpoints.autoscaling.k8s.io
spec:
  group: autoscaling.k8s.io
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              targetRef:
                type: object
                properties:
                  apiVersion:
                    type: string
                  kind:
                    type: string
                  name:
                    type: string
              vpaObjectName:
                type: string
              containerName:
                type: string
          status:
            type: object
            properties:
              lastUpdateTime:
                type: string
                format: date-time
              version:
                type: string
              cpuHistogram:
                type: object
              memoryHistogram:
                type: object
              firstSampleStart:
                type: string
                format: date-time
              lastSampleStart:
                type: string
                format: date-time
              totalSamplesCount:
                type: integer
  scope: Namespaced
  names:
    plural: verticalpodautoscalercheckpoints
    singular: verticalpodautoscalercheckpoint
    kind: VerticalPodAutoscalerCheckpoint
    shortNames:
    - vpacheckpoint