apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  annotations:
    policies.kyverno.io/category: Istio
    policies.kyverno.io/description: This policy ensures namespaces starting with
      'at' have the required Istio revision label for proper sidecar injection. The
      label istio.io/rev=asm-1-23 is required for Istio to know which version of the
      sidecar to inject.
    policies.kyverno.io/severity: medium
    policies.kyverno.io/title: Required Istio Revision Label
  name: require-istio-revision-label
spec:
  background: true
  mutateExistingOnPolicyUpdate: true
  rules:
  - name: add-istio-revision-label
    match:
      resources:
        kinds:
        - Namespace
        name: "at[0-9]{5}"
    mutate:
      targets:
      - apiVersion: v1
        kind: Namespace
      patchStrategicMerge:
        metadata:
          labels:
            istio.io/rev: asm-1-23
  - name: check-istio-revision-label
    match:
      resources:
        kinds:
        - Namespace
        name: "at[0-9]{5}"
    validate:
      message: Namespaces starting with 'at' followed by 5 numbers must have the label istio.io/rev=asm-1-23
      pattern:
        metadata:
          labels:
            istio.io/rev: asm-1-23
  validationFailureAction: Audit
