apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - pod-security.yaml
  - network-policies.yaml
  - resource-quotas.yaml
  - image-verification.yaml
  - istio-mtls.yaml
  - istio-rev-label.yaml
  - disallow-latest-tag.yaml
  - require-labels.yaml
  - check-deprecated-apis.yaml
  - kyverno-rbac.yaml
  - pod-antiaffinity.yaml
  # - node-affinity-spot.yaml
  # - spot-tolerations.yaml 