apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kyverno-admin-role
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["authentication.k8s.io"]
  resources: ["tokenreviews"]
  verbs: ["create"]
- apiGroups: ["authorization.k8s.io"]
  resources: ["subjectaccessreviews"]
  verbs: ["create"]
- apiGroups: ["kyverno.io"]
  resources: ["clusterpolicies", "policies", "policyexceptions", "clusterreports", "reports"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
- apiGroups: ["wgpolicyk8s.io"]
  resources: ["clusterpolicyreports", "policyreports"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
- apiGroups: ["security.istio.io"]
  resources: ["peerauthentications"]
  verbs: ["get", "list", "watch"]
---
# Role specifically for the reports controller
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kyverno-reports-role
rules:
- apiGroups: ["security.istio.io"]
  resources: ["peerauthentications"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kyverno-admin-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kyverno-admin-role
subjects:
- kind: ServiceAccount
  name: kyverno
  namespace: kyverno
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kyverno-reports-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kyverno-reports-role
subjects:
- kind: ServiceAccount
  name: kyverno-reports-controller
  namespace: kyverno 