---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: audit-pod-affinity-spot
spec:
  rules:
  - match:
      resources:
        kinds:
        - Pod
        namespaces:
        - "at[0-9]{5}"
    mutate:
      patchStrategicMerge:
        spec:
          affinity:
            nodeAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
              - preference:
                  matchExpressions:
                  - key: kubernetes.azure.com/scalesetpriority
                    operator: In
                    values:
                    - spot
                weight: 100
    name: prefer-spot-instances
  validationFailureAction: Audit