apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: pod-security-controls
spec:
  rules:
  - match:
      resources:
        kinds:
        - Pod
        namespaces:
        - "at[0-9]{5}"
    name: restrict-privileged
    validate:
      pattern:
        spec:
          containers:
          - securityContext:
              privileged: false
  validationFailureAction: Audit