apiVersion: karpenter.azure.com/v1alpha2
kind: AKSNodeClass
metadata:
  name: system-nodes
spec:
  imageFamily: AzureLinux
  osDiskSizeGB: 128
  customData: |
    #cloud-config
    package_update: true
    package_upgrade: true
    packages:
      - docker.io
      - docker-compose
---
apiVersion: karpenter.azure.com/v1alpha2
kind: AKSNodeClass
metadata:
  name: spot-nodes
spec:
  imageFamily: AzureLinux
  osDiskSizeGB: 128
  customData: |
    #cloud-config
    package_update: true
    package_upgrade: true
    packages:
      - docker.io
      - docker-compose
---
apiVersion: karpenter.azure.com/v1alpha2
kind: AKSNodeClass
metadata:
  name: gpu-nodes
spec:
  imageFamily: AzureLinux
  osDiskSizeGB: 256
  customData: |
    #cloud-config
    package_update: true
    package_upgrade: true
    packages:
      - docker.io
      - docker-compose
      - nvidia-docker2
---
apiVersion: karpenter.azure.com/v1alpha2
kind: AKSNodeClass
metadata:
  name: batch-nodes
spec:
  imageFamily: AzureLinux
  osDiskSizeGB: 128
  customData: |
    #cloud-config
    package_update: true
    package_upgrade: true
    packages:
      - docker.io
      - docker-compose
---
apiVersion: karpenter.azure.com/v1alpha2
kind: AKSNodeClass
metadata:
  name: infra-nodes
spec:
  imageFamily: AzureLinux
  osDiskSizeGB: 128
  customData: |
    #cloud-config
    package_update: true
    package_upgrade: true
    packages:
      - docker.io
      - docker-compose 