apiVersion: batch/v1
kind: Job
metadata:
  name: test-job-with-label
  labels:
    skip-verify: "true"
spec:
  template:
    metadata:
      labels:
        skip-verify: "true"
    spec:
      containers:
      - name: echo
        image: my.registry.com/hello-world:latest
      restartPolicy: Never 