apiVersion: batch/v1
kind: Job
metadata:
  name: test-job
spec:
  template:
    spec:
      containers:
      - name: echo
        image: my.registry.com/hello-world:latest
      restartPolicy: Never 