apiVersion: v1
kind: Pod
metadata:
  name: test-ubs-pod
  namespace: atlas
spec:
  containers:
  - name: app
    image: container-registry.ubs.net/my-app:1.0
    command: ["sleep"]
    args: ["infinity"]
  initContainers:
  - name: init-app
    image: container-registry.ubs.net/init-app:latest
    command: ["sh", "-c", "echo 'Initializing'"] 