apiVersion: v1
kind: Pod
metadata:
  name: test-xxx-pod-double
  namespace: atlas
spec:
  containers:
  - name: app
    image: xxxleaseacr.azurecr.io/my-app:1.0
    command: ["sleep"]
    args: ["infinity"]
  initContainers:
  - name: init-app
    image: xxxleaseacr.azurecr.io/init-app:latest
    command: ["sh", "-c", "echo 'Initializing'"] 