apiVersion: batch/v1
kind: Job
metadata:
  name: test-job-exact-registry
  namespace: default
spec:
  template:
    spec:
      containers:
      - name: test-container
        image: my.registry.com/test-image:latest
      restartPolicy: Never
  backoffLimit: 1 