apiVersion: batch/v1
kind: Job
metadata:
  name: test-job-contains-registry
  namespace: default
spec:
  template:
    spec:
      containers:
      - name: test-container
        image: docker.io/someuser/not-my.registry.com-text:latest
      restartPolicy: Never
  backoffLimit: 1 