apiVersion: batch/v1
kind: Job
metadata:
  name: test-job-partial-match
  namespace: default
spec:
  template:
    spec:
      containers:
      - name: test-container
        image: docker.io/someuser/contains-my.registry.com:latest
      restartPolicy: Never
  backoffLimit: 1 