apiVersion: v1
kind: Pod
metadata:
  name: nginx-privileged
  namespace: at12345-dev
  labels:
    app.kubernetes.io/name: nginx-privileged
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    securityContext:
      privileged: true 