apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cert-injector
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: cert-injector
  template:
    metadata:
      labels:
        app: cert-injector
    spec:
      # Add tolerations for all node types
      tolerations:
      - key: "CriticalAddonsOnly"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "workload-type"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "kubernetes.azure.com/scalesetpriority"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "node.kubernetes.io/not-ready"
        operator: "Exists"
        effect: "NoExecute"
      - key: "node.kubernetes.io/unreachable"
        operator: "Exists"
        effect: "NoExecute"
      # Rest of your existing DaemonSet spec
      containers:
      - name: cert-injector
        image: mcr.microsoft.com/cbl-mariner/base/core:2.0