apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: policy-repo
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/your-org/policies  # Your repo URL
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: policies
  namespace: flux-system
spec:
  interval: 10m
  path: ./clusters/dev  # Points to dev environment
  prune: true
  sourceRef:
    kind: GitRepository
    name: policy-repo 