apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../policies/base

patches:
  - target:
      kind: ClusterPolicy
      name: enforce-strict-mtls
    patch: |
      - op: replace
        path: /spec/validationFailureAction
        value: audit
  - target:
      kind: ClusterPolicy
      name: require-istio-revision-label
    patch: |
      - op: replace
        path: /spec/validationFailureAction
        value: audit 