apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: azureserviceoperator-system
namePrefix: dev-

resources:
  - ../../base/cluster-template

configMapGenerator:
  - name: cluster-config
    behavior: merge
    literals:
      - CLUSTER_NAME=dev-aks-01
      - LOCATION=eastus2
      - RESOURCE_GROUP=rg-aks-dev
      - K8S_VERSION=1.28.3
      - USER_ASSIGNED_IDENTITY_NAME=dev-aks-identity
      - ADMIN_GROUP_ID=your-admin-group-id
      - NETWORK_SERVICE_CIDR=172.16.0.0/16
      - NETWORK_DNS_SERVICE_IP=172.16.0.10
      - NETWORK_POD_CIDR=10.244.0.0/16
      - SYSTEM_NODEPOOL_VM_SIZE=Standard_D4s_v3
      - SYSTEM_NODEPOOL_COUNT=1
      - SYSTEM_NODEPOOL_MIN_COUNT=1
      - SYSTEM_NODEPOOL_MAX_COUNT=2
      - SYSTEM_NODEPOOL_MAX_PODS=30
      - USER_NODEPOOL_VM_SIZE=Standard_D4s_v3
      - USER_NODEPOOL_COUNT=1
      - USER_NODEPOOL_MIN_COUNT=1
      - USER_NODEPOOL_MAX_COUNT=3
      - USER_NODEPOOL_MAX_PODS=30
      - ADDONS_KEYVAULT_ROTATION_INTERVAL=2m
      - ADDONS_MONITORING_WORKSPACE_ID=/subscriptions/sub-id/resourceGroups/rg-monitoring-dev/providers/Microsoft.OperationalInsights/workspaces/law-aks-dev
      - AUTO_UPGRADE_CHANNEL=patch
      - AUTO_UPGRADE_NODE_OS_CHANNEL=SecurityPatch

replacements:
  # Basic cluster settings
  - source:
      kind: ConfigMap
      name: cluster-config
      fieldPath: data.CLUSTER_NAME
    targets:
      - select:
          kind: ManagedCluster
        fieldPaths:
          - metadata.name
          - spec.dnsPrefix

  - source:
      kind: ConfigMap
      name: cluster-config
      fieldPath: data.LOCATION
    targets:
      - select:
          kind: ManagedCluster
        fieldPaths:
          - spec.location

  - source:
      kind: ConfigMap
      name: cluster-config
      fieldPath: data.RESOURCE_GROUP
    targets:
      - select:
          kind: ManagedCluster
        fieldPaths:
          - spec.owner.name

  - source:
      kind: ConfigMap
      name: cluster-config
      fieldPath: data.K8S_VERSION
    targets:
      - select:
          kind: ManagedCluster
        fieldPaths:
          - spec.kubernetesVersion

  # Network settings
  - source:
      kind: ConfigMap
      name: cluster-config
      fieldPath: data.NETWORK_SERVICE_CIDR
    targets:
      - select:
          kind: ManagedCluster
        fieldPaths:
          - spec.networkProfile.serviceCidr

  - source:
      kind: ConfigMap
      name: cluster-config
      fieldPath: data.NETWORK_DNS_SERVICE_IP
    targets:
      - select:
          kind: ManagedCluster
        fieldPaths:
          - spec.networkProfile.dnsServiceIP

  - source:
      kind: ConfigMap
      name: cluster-config
      fieldPath: data.NETWORK_POD_CIDR
    targets:
      - select:
          kind: ManagedCluster
        fieldPaths:
          - spec.networkProfile.podCidr

  # System nodepool settings
  - source:
      kind: ConfigMap
      name: cluster-config
      fieldPath: data.SYSTEM_NODEPOOL_VM_SIZE
    targets:
      - select:
          kind: ManagedCluster
        fieldPaths:
          - spec.agentPoolProfiles.[name=sysnpl1].vmSize

  - source:
      kind: ConfigMap
      name: cluster-config
      fieldPath: data.SYSTEM_NODEPOOL_COUNT
    targets:
      - select:
          kind: ManagedCluster
        fieldPaths:
          - spec.agentPoolProfiles.[name=sysnpl1].count

  - source:
      kind: ConfigMap
      name: cluster-config
      fieldPath: data.SYSTEM_NODEPOOL_MIN_COUNT
    targets:
      - select:
          kind: ManagedCluster
        fieldPaths:
          - spec.agentPoolProfiles.[name=sysnpl1].minCount

  - source:
      kind: ConfigMap
      name: cluster-config
      fieldPath: data.SYSTEM_NODEPOOL_MAX_COUNT
    targets:
      - select:
          kind: ManagedCluster
        fieldPaths:
          - spec.agentPoolProfiles.[name=sysnpl1].maxCount

  - source:
      kind: ConfigMap
      name: cluster-config
      fieldPath: data.SYSTEM_NODEPOOL_MAX_PODS
    targets:
      - select:
          kind: ManagedCluster
        fieldPaths:
          - spec.agentPoolProfiles.[name=sysnpl1].maxPods

  # User nodepool settings
  - source:
      kind: ConfigMap
      name: cluster-config
      fieldPath: data.USER_NODEPOOL_VM_SIZE
    targets:
      - select:
          kind: ManagedCluster
        fieldPaths:
          - spec.agentPoolProfiles.[name=usrnpl1].vmSize

  - source:
      kind: ConfigMap
      name: cluster-config
      fieldPath: data.USER_NODEPOOL_COUNT
    targets:
      - select:
          kind: ManagedCluster
        fieldPaths:
          - spec.agentPoolProfiles.[name=usrnpl1].count

  - source:
      kind: ConfigMap
      name: cluster-config
      fieldPath: data.USER_NODEPOOL_MIN_COUNT
    targets:
      - select:
          kind: ManagedCluster
        fieldPaths:
          - spec.agentPoolProfiles.[name=usrnpl1].minCount

  - source:
      kind: ConfigMap
      name: cluster-config
      fieldPath: data.USER_NODEPOOL_MAX_COUNT
    targets:
      - select:
          kind: ManagedCluster
        fieldPaths:
          - spec.agentPoolProfiles.[name=usrnpl1].maxCount

  - source:
      kind: ConfigMap
      name: cluster-config
      fieldPath: data.USER_NODEPOOL_MAX_PODS
    targets:
      - select:
          kind: ManagedCluster
        fieldPaths:
          - spec.agentPoolProfiles.[name=usrnpl1].maxPods

  # Addon settings
  - source:
      kind: ConfigMap
      name: cluster-config
      fieldPath: data.ADDONS_KEYVAULT_ROTATION_INTERVAL
    targets:
      - select:
          kind: ManagedCluster
        fieldPaths:
          - spec.addonProfiles.azureKeyvaultSecretsProvider.config.rotationPollInterval

  - source:
      kind: ConfigMap
      name: cluster-config
      fieldPath: data.ADDONS_MONITORING_WORKSPACE_ID
    targets:
      - select:
          kind: ManagedCluster
        fieldPaths:
          - spec.addonProfiles.omsagent.config.logAnalyticsWorkspaceResourceID

  # Auto-upgrade settings
  - source:
      kind: ConfigMap
      name: cluster-config
      fieldPath: data.AUTO_UPGRADE_CHANNEL
    targets:
      - select:
          kind: ManagedCluster
        fieldPaths:
          - spec.autoUpgradeProfile.upgradeChannel

  - source:
      kind: ConfigMap
      name: cluster-config
      fieldPath: data.AUTO_UPGRADE_NODE_OS_CHANNEL
    targets:
      - select:
          kind: ManagedCluster
        fieldPaths:
          - spec.autoUpgradeProfile.nodeOSUpgradeChannel

patches:
  - patch: |-
      apiVersion: containerservice.azure.com/v1api20240901
      kind: ManagedCluster
      metadata:
        name: aks-cluster
      spec:
        apiServerAccessProfile:
          enablePrivateCluster: false
        securityProfile:
          defender:
            securityMonitoring:
              enabled: false
        addonProfiles:
          azurepolicy:
            enabled: false
          omsagent:
            enabled: false
    target:
      kind: ManagedCluster
      name: aks-cluster

labels:
  - pairs:
      environment: development
