apiVersion: v1
kind: Namespace
metadata:
  name: myapp-dev-cloudability    # Replace with your namespace

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloudability
  namespace: myapp-dev-cloudability
  labels:
    azure.workload.identity/use: "true"
  annotations:
    azure.workload.identity/client-id: "00000000-0000-0000-0000-000000000000"    # Replace with managed identity client ID
    azure.workload.identity/tenant-id: "11111111-1111-1111-1111-111111111111"    # Replace with your tenant ID

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cloudability-metrics-agent
  namespace: kube-system
rules:
- apiGroups:
  - ""
  - "extensions"
  - "apps"
  - "batch"
  resources:
    - "namespaces"
    - "replicationcontrollers"
    - "services"
    - "nodes"
    - "nodes/spec"
    - "pods"
    - "jobs"
    - "cronjobs"
    - "persistentvolumes"
    - "persistentvolumeclaims"
    - "deployments"
    - "replicasets"
    - "daemonsets"
  verbs:
    - "get"
    - "watch"
    - "list"
- apiGroups: [""]
  resources:
    - "services/proxy"
    - "pods/proxy"
    - "nodes/proxy"
    - "nodes/stats"
    - "nodes/metrics"
  verbs:
    - "get"
    - "list"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cloudability-metrics-agent
  namespace: kube-system
subjects:
- kind: ServiceAccount
  name: cloudability
  namespace: myapp-dev-cloudability
roleRef:
  kind: ClusterRole
  name: cloudability-metrics-agent
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cloudability-metrics-agent
  namespace: myapp-dev-cloudability
rules:
- apiGroups: ["*"]
  resources:
    - "pods"
    - "pods/log"
  verbs:
    - "get"
    - "list"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cloudability-metrics-agent
  namespace: myapp-dev-cloudability
subjects:
- kind: ServiceAccount
  name: cloudability
  namespace: myapp-dev-cloudability
roleRef:
  kind: Role
  name: cloudability-metrics-agent
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudability-metrics-agent
  namespace: myapp-dev-cloudability
  labels:
    app: cloudability-metrics-agent
spec:
  selector:
    matchLabels:
      app: cloudability-metrics-agent
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: cloudability-metrics-agent
        azure.workload.identity/use: "true"
      annotations:
        seccomp.security.alpha.kubernetes.io/pod: runtime/default
    spec:
      serviceAccountName: cloudability
      securityContext:
        seccompProfile:
          type: RuntimeDefault
        fsGroup: 10000
      containers:
        - name: cloudability-metrics-agent
          image: cloudability/metrics-agent:latest
          imagePullPolicy: Always
          securityContext:
            runAsUser: 10000
            runAsNonRoot: true
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
            allowPrivilegeEscalation: false
          resources:
            requests:
              memory: "2Gi"
              cpu: "500m"
            limits:
              memory: "4Gi"
              cpu: "1"
          livenessProbe:
            exec:
              command:
                - touch
                - /tmp/healthy
            initialDelaySeconds: 120
            periodSeconds: 600
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command:
                - touch
                - /tmp/healthy
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 5
          args:
            - "kubernetes"
          env:
            - name: CLOUDABILITY_CLUSTER_NAME
              value: "my-aks-cluster-name"    # Replace with your cluster name
            - name: CLOUDABILITY_CUSTOM_AZURE_BLOB_CONTAINER_NAME
              value: "metrics-container"       # Replace with your blob container name
            - name: CLOUDABILITY_CUSTOM_AZURE_BLOB_URL
              value: "mystorageaccount.blob.core.windows.net"    # Replace with your storage account URL
            - name: CLOUDABILITY_CUSTOM_AZURE_TENANT_ID
              value: "11111111-1111-1111-1111-111111111111"     # Replace with your tenant ID
            - name: CLOUDABILITY_CUSTOM_AZURE_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['azure.workload.identity/client-id']
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
