apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: prevent-httproute-hostname-hijack
spec:
  validationFailureAction: Enforce
  background: false
  rules:
    - name: enforce-namespace-hostname
      match:
        resources:
          kinds:
            - HTTPRoute
          operations:
            - CREATE
            - UPDATE
      validate:
        message: "HTTPRoute hostname must start with the namespace name"
        deny:
          conditions:
            - key: "{{ regex_match('^{{request.object.metadata.namespace}}-.*', request.object.spec.hostnames[0]) }}"
              operator: Equals
              value: false