apiVersion: containerservice.azure.com/v1api20240901
kind: ManagedCluster
metadata:
  name: placeholder-name
  namespace: azureserviceoperator-system
spec:
  location: placeholder-location
  owner:
    name: placeholder-resource-group
  dnsPrefix: placeholder-dns-prefix
  kubernetesVersion: placeholder-k8s-version
  identity:
    type: UserAssigned
    userAssignedIdentities:
      - reference:
          armId: placeholder-control-plane-identity
  servicePrincipalProfile:
    clientId: placeholder-runtime-client-id
    objectId: placeholder-runtime-object-id
  aadProfile:
    enableAzureRBAC: true
    managed: true
    adminGroupObjectIDs: ["placeholder-admin-group"]
  enableRBAC: true
  disableLocalAccounts: true
  networkProfile:
    networkPlugin: azure
    networkPluginMode: overlay
    networkPolicy: cilium
    networkDataplane: cilium
    serviceCidr: placeholder-service-cidr
    dnsServiceIP: placeholder-dns-service-ip
    podCidr: placeholder-pod-cidr
    ipFamilies: ["IPv4"]
    loadBalancerSku: standard
    outboundType: placeholder-outbound-type
  apiServerAccessProfile:
    enablePrivateCluster: true
    enablePrivateClusterPublicFQDN: true
  oidcIssuerProfile:
    enabled: true
  securityProfile:
    defender:
      securityMonitoring:
        enabled: placeholder-defender-enabled
      logAnalyticsWorkspaceResourceID: placeholder-workspace-id-defender
    workloadIdentity:
      enabled: placeholder-workload-identity-enabled
    customCATrustConfig:
      enabled: true
  serviceMeshProfile:
    mode: placeholder-service-mesh-mode
    istio:
      components:
        ingressGateways:
          - enabled: placeholder-service-mesh-ingress-enabled
            mode: placeholder-service-mesh-ingress-mode
      revisions:
        - placeholder-service-mesh-revision
  agentPoolProfiles:
    - name: placeholder-system-nodepool-name
      mode: System
      count: placeholder-system-nodepool-count
      minCount: placeholder-system-nodepool-min-count
      maxCount: placeholder-system-nodepool-max-count
      enableAutoScaling: true
      vmSize: placeholder-system-nodepool-vmsize
      availabilityZones: placeholder-system-nodepool-zones
      osDiskType: Managed
      osDiskSizeGB: placeholder-system-nodepool-disk-size
      osType: Linux
      osSKU: AzureLinux
      maxPods: placeholder-system-nodepool-maxpods
      nodeTaints:
        - placeholder-system-nodepool-taints
      enableCustomCATrust: placeholder-system-nodepool-custom-ca
      type: VirtualMachineScaleSets
      orchestratorVersion: placeholder-k8s-version
    - name: placeholder-user-nodepool-name
      mode: User
      count: placeholder-user-nodepool-count
      minCount: placeholder-user-nodepool-min-count
      maxCount: placeholder-user-nodepool-max-count
      enableAutoScaling: true
      vmSize: placeholder-user-nodepool-vmsize
      availabilityZones: placeholder-user-nodepool-zones
      osDiskType: Managed
      osDiskSizeGB: placeholder-user-nodepool-disk-size
      osType: Linux
      osSKU: AzureLinux
      maxPods: placeholder-user-nodepool-maxpods
      enableCustomCATrust: placeholder-user-nodepool-custom-ca
      type: VirtualMachineScaleSets
      orchestratorVersion: placeholder-k8s-version
      nodeLabels:
        kubernetes.azure.com/scalesetpriority: spot
      nodeTaints:
        - kubernetes.azure.com/scalesetpriority=spot:NoSchedule
  addonProfiles:
    azureKeyvaultSecretsProvider:
      enabled: placeholder-keyvault-enabled
      config:
        enableSecretRotation: placeholder-keyvault-rotation
        rotationPollInterval: placeholder-rotation-interval
    azurepolicy:
      enabled: placeholder-policy-enabled
    omsagent:
      enabled: placeholder-monitoring-enabled
      config:
        logAnalyticsWorkspaceResourceID: placeholder-workspace-id
  autoUpgradeProfile:
    upgradeChannel: placeholder-upgrade-channel
    nodeOSUpgradeChannel: placeholder-os-channel
  sshPublicKey:
    keyVaultSecretRef:
      name: placeholder-ssh-secret
      vault:
        name: placeholder-keyvault-name
        resourceGroup: placeholder-keyvault-rg
  uptimeSLATier: placeholder-uptime-sla
