name: "API trigger namespace onboarding"

parameters:

- name: action

  type: string

  default: 'add'

  values:

    - add

    - remove

    - modify

- name: swci

  type: string

  default: 'at54231'

- name: suffix

  type: string

  default: 'default'

- name: region

  type: string

  default: 'switzerlandnorth'

  values:

    - centralus

    - eastus2

    - eastasia

    - southeastasia

    - northeurope

    - westeurope

    - switzerlandnorth

- name: opEnvironment

  type: string

  default: 'preprod'

  values:

    - test

    - dev

    - preprod

    - prod

- name: resourceQuotaCPU

  type: string

  default: '1'

- name: resourceQuotaMemoryGB

  type: string

  default: '1'

- name: billingReference

  type: string

  default: 'AB-BC-ABCDE-ABCDE'

- name: source

  type: string

  default: 'GSNOW'

- name: swcID

  type: string

  default: 'AA98765'

- name: dataClassification

  type: string

  default: 'public'

  values:

    - public

    - internal

    - confidential

    - strictly-confidential

    - None

- name: requestedBy

  type: string

  default: david.gardiner@ubs.com

- name: namespacename

  type: string

  default: at54231-dev-pimtest

- name: fulldomainname

  type: string

  default: ' '

- name: StageName

  type: string

  default: All_Stages

  values:

   - All_Stages

   - deploynamespace

   - rbacrolebinding

   - apptesturl

   - disasterrecoveryrbacrolebinding

# Trigger configuration
trigger: none

pr: none

pool:

  name: HostedinAzure-Linux-UK8S-ManagedAKS-Dev

  demands:

    - standard

 

resources:

  repositories:

    - repository: pipeline

      type: git

      name: uk8s-cluster-config

      ref: refs/tags/v0.1.19 # please set tag after merging to main.

      # ref: refs/heads/feature/gitops-test # please set tag after merging to main.

     

stages:

- template: 'pipelines/pipeline/entrypoint.yml@pipeline'

  parameters:

    StageName: ${{ parameters.StageName }}

    serviceConnectionName: ${{ parameters.serviceConnectionName }}

    action: ${{ parameters.action }}

    swci: ${{ parameters.swci }}

    suffix: ${{ parameters.suffix }}

    region: ${{ parameters.region }}

    opEnvironment: ${{ parameters.opEnvironment }}

    resourceQuotaCPU: ${{ parameters.resourceQuotaCPU }}

    resourceQuotaMemoryGB: ${{ parameters.resourceQuotaMemoryGB }}

    billingReference: ${{ parameters.billingReference }}

    source: ${{ parameters.source }}

    swcID: ${{ parameters.swcID }}

    dataClassification: ${{ parameters.dataClassification }}

    requestedBy: ${{ parameters.requestedBy }}

    namespacename: ${{ parameters.namespacename }}

    aksclusterresourceid: ${{ parameters.aksclusterresourceid }}

    fulldomainname: ${{ parameters.fulldomainname }}