apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: simplified-image-policy
  annotations:
    policies.kyverno.io/title: Image Push Job Generator
    pod-policies.kyverno.io/autogen-controllers: none
    policies.kyverno.io/category: Sample
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
    kyverno.io/kyverno-version: 1.7.2
    policies.kyverno.io/minversion: 1.6.0
    kyverno.io/kubernetes-version: "1.23"
    policies.kyverno.io/description: >-
      This policy verifies images in ACR and generates jobs with image information
      for missing images.
spec:
  background: false
  rules:
    - name: generate-push-job
      match:
        any:
        - resources:
            kinds:
            - Pod
      exclude:
        any:
        - resources:
            selector:
              matchLabels:
                skip-verify: "true"
      preconditions:
        all:
        - key: "{{ request.object.kind }}"
          operator: Equals
          value: Pod
        # Check if a job for this Pod kind already exists
        - key: "{{ request.operation }}"
          operator: Equals
          value: CREATE

      generate:
        apiVersion: batch/v1
        kind: Job
        # Simple name pattern that will be compliant
        name: "image-push-{{ request.object.metadata.name }}"
        namespace: "{{request.namespace}}"
        synchronize: false
        data:
          apiVersion: batch/v1
          kind: Job
          metadata:
            # Using generateName for unique naming when applying the job
            name: "image-push-{{ request.object.metadata.name }}"
            labels:
              skip-verify: "true"
              pod-kind: "{{ request.object.kind }}"
              from-pod: "{{ request.object.metadata.name }}"
          spec:
            template:
              metadata:
                labels:
                  skip-verify: "true"
              spec:
                containers:
                - name: push-image
                  image: mcr.microsoft.com/azure-cli
                  env:
                  - name: POD_NAME
                    value: "{{ request.object.metadata.name }}"
                  - name: POD_NAMESPACE
                    value: "{{ request.namespace }}"
                  - name: IMAGE_NAME
                    value: "{{ request.object.spec.containers[0].image }}"
                  command:
                  - /bin/bash
                  - -c
                  - |
                    echo "Job processing image information for pod $POD_NAME in namespace $POD_NAMESPACE"
                    echo "IMAGE_NAME: $IMAGE_NAME"
                    
                    # Extract image parts in a way that handles various formats
                    IMAGE_PATH=$(echo "$IMAGE_NAME" | sed 's/^.*\/\|:.*$//g' | tr '/:@.' '-')
                    echo "Normalized image path: $IMAGE_PATH"
                    
                    # Ensure RFC 1123 compliance - lowercase and valid characters only
                    RFC_NAME=$(echo "$IMAGE_PATH" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9-]/-/g')
                    # Ensure it doesn't start or end with hyphen
                    RFC_NAME=$(echo "$RFC_NAME" | sed 's/^-//;s/-$//')
                    echo "RFC 1123 compliant name: $RFC_NAME"
                    
                    echo "Performing actions based on image information..."
                    sleep 30
                restartPolicy: Never
            backoffLimit: 3 
            # Add a TTL to automatically clean up completed jobs
            ttlSecondsAfterFinished: 3600