{
 "title": "Image Push Jobs Dashboard",
 "tags": [
  "kubernetes",
  "jobs",
  "image-push"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_job_info{job_name=~\"image-push-job-.*\"}, namespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "Image Push Job Failures",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_job_status_failed{job_name=~\"image-push-job-.*\"}) by (namespace, job_name)",
     "legendFormat": "{{namespace}}/{{job_name}}"
    }
   ]
  },
  {
   "title": "Failed Image Push Jobs",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "kube_job_status_failed{job_name=~\"image-push-job-.*\"} > 0"
    }
   ]
  },
  {
   "title": "Successful Jobs by Namespace",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_job_status_succeeded{job_name=~\"image-push-job-.*\"}) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Failed Jobs by Namespace",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_job_status_failed{job_name=~\"image-push-job-.*\"}) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  }
 ]
}