apiVersion: v1
kind: Pod
metadata:
  name: test-app-pod
  namespace: default
  labels:
    app: test-app
spec:
  containers:
  - name: app-container
    image: nginx:1.19.3
    ports:
    - containerPort: 80
---
apiVersion: batch/v1
kind: Job
metadata:
  name: test-image-env-job
  namespace: default
spec:
  template:
    spec:
      containers:
      - name: job-container
        image: busybox:latest
        command: ["sh", "-c"]
        args:
        - |
          echo "Job processing image information:"
          echo "IMAGE_NAME: $IMAGE_NAME"
          echo "IMAGE_TAG: $IMAGE_TAG"
          echo "Performing actions based on image information..."
          sleep 30
      restartPolicy: Never
  backoffLimit: 0 