apiVersion: v1
kind: Pod
metadata:
  name: test-app-pod
  namespace: default
  labels:
    app: test-app
spec:
  containers:
  - name: app-container
    image: nginx:1.19.3
    ports:
    - containerPort: 80