apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-spot-deployment
  namespace: test-spot-ns
  labels:
    app: test-spot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-spot
  template:
    metadata:
      labels:
        app: test-spot
    spec:
      containers:
      - name: nginx
        image: nginx:1.21
        ports:
        - containerPort: 80 