apiVersion: v1
kind: Namespace
metadata:
  name: test-high-perf
  labels:
    workload-type: high-performance
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-compute-intensive
  namespace: test-high-perf
spec:
  replicas: 2
  selector:
    matchLabels:
      app: compute-job
  template:
    metadata:
      labels:
        app: compute-job
    spec:
      containers:
      - name: compute-worker
        image: nginx:1.25  # Using nginx as a placeholder
        resources:
          requests:
            cpu: "4"
            memory: "8Gi"
          limits:
            cpu: "8"
            memory: "16Gi"
        # In a real scenario, you might use a compute-intensive image
        # and add compute-intensive tasks 