apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kyverno-reports-controller-gateway
  labels:
    app.kubernetes.io/name: kyverno
    app.kubernetes.io/component: reports-controller
rules:
- apiGroups: ["gateway.networking.k8s.io"]
  resources: ["gateways"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kyverno-reports-controller-gateway
  labels:
    app.kubernetes.io/name: kyverno
    app.kubernetes.io/component: reports-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kyverno-reports-controller-gateway
subjects:
- kind: ServiceAccount
  name: kyverno-reports-controller
  namespace: kyverno


---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kyverno-reports-controller-gateway
  labels:
    app.kubernetes.io/name: kyverno
    app.kubernetes.io/component: reports-controller
  annotations:
    # Azure RBAC compatibility
    rbac.authorization.k8s.io/autoupdate: "true"
rules:
- apiGroups: ["gateway.networking.k8s.io"]
  resources: ["gateways"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kyverno-reports-controller-gateway
  labels:
    app.kubernetes.io/name: kyverno
    app.kubernetes.io/component: reports-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kyverno-reports-controller-gateway
subjects:
- kind: ServiceAccount
  name: kyverno-reports-controller
  namespace: kyverno

---

apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-gateway-labels
spec:
  validationFailureAction: enforce
  background: true
  rules:
  - name: require-app-label
    match:
      any:
      - resources:
          kinds:
          - Gateway
          apiVersions:
          - "gateway.networking.k8s.io/v1beta1"
    validate:
      message: "Gateway must have an 'app' label"
      pattern:
        metadata:
          labels:
            app: "?*"