apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: verify-images
spec:
  validationFailureAction: audit
  rules:
    - name: verify-signatures
      match:
        resources:
          kinds:
            - Pod
      verifyImages:
      - imageReferences:
        - "*"
        attestors:
        - entries:
          - keyless:
              subject: "https://github.com/*"
              issuer: "https://token.actions.githubusercontent.com" 