apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kyverno-policies-preprod
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./kustomize/overlays/preprod
  prune: true
  sourceRef:
    kind: GitRepository
    name: kyverno-policies
  validation: client
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: kyverno-env-vars-preprod 