apiVersion: v1
kind: Pod
metadata:
  name: nginx-no-limits
  namespace: at12345-dev
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    # Violation: No resource limits or requests specified 