apiVersion: v1
kind: Pod
metadata:
  name: nginx-with-limits
  namespace: at12345-dev
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    resources:
      limits:
        memory: "256Mi"
        cpu: "500m"
      requests:
        memory: "128Mi"
        cpu: "250m" 