apiVersion: batch/v1
kind: Job
metadata:
  name: image-push-job-test-pod-multi
  namespace: default
spec:
  template:
    spec:
      containers:
      - name: image-push
        image: docker.io/nginx:latest
      restartPolicy: Never
  backoffLimit: 4
