apiVersion: containerservice.azure.com/v1api20240901
kind: ManagedCluster
metadata:
  name: aks-cluster
spec:
  apiServerAccessProfile:
    enablePrivateCluster: true  # Direct boolean
  securityProfile:
    defender:
      securityMonitoring:
        enabled: true  # Direct boolean
  addonProfiles:
    azurepolicy:
      enabled: true  # Direct boolean
