apiVersion: v1
kind: Service
metadata:
  name: kyverno-svc
  namespace: kyverno
spec:
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: https
  - name: metrics-port
    port: 8000
    protocol: TCP
    targetPort: metrics-port 