apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kyverno-service-monitor
  namespace: kyverno
  labels:
    app: kyverno
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: admission-controller
      app.kubernetes.io/instance: kyverno
      app.kubernetes.io/part-of: kyverno
  namespaceSelector:
    matchNames:
      - kyverno
  endpoints:
    - port: metrics-port
      path: /metrics
      interval: 30s 