apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: generate-unique-job-per-image-fixed
  annotations:
    policies.kyverno.io/title: Generate Unique Job Per Image (Fixed)
    policies.kyverno.io/description: >-
      Creates exactly one Kubernetes Job per unique container image using base64 encoding
      for deterministic name generation. Uses image string manipulation to ensure
      RFC 1123 compliant names.
spec:
  admission: true
  background: true
  rules:
  - name: generate-image-unique-job
    match:
      any:
      - resources:
          kinds:
          - Pod
          namespaces:
          - default
          - test-namespace
    exclude:
      any:
      - resources:
          namespaces:
          - kyverno
          - kube-system
      - resources:
          selector:
            matchLabels:
              generated-by: unique-job-per-image-policy
    preconditions:
      all:
      - key: "{{ request.object.metadata.ownerReferences[] || `[]` | length(@) }}"
        operator: Equals
        value: 0
    generate:
      synchronize: false
      apiVersion: batch/v1
      kind: Job
      # Use base64 encoding and take substring for deterministic naming
      # Replace special characters to ensure RFC compliance
      name: "img-{{ base64_encode(request.object.spec.containers[0].image) | truncate(@, `8`) | replace_all(@, '+', 'x') | replace_all(@, '/', 'y') | replace_all(@, '=', 'z') | lower(@) }}"
      namespace: "{{ request.namespace }}"
      data:
        metadata:
          labels:
            generated-by: unique-job-per-image-policy
            source-pod: "{{ request.object.metadata.name }}"
            image-processed: "true"
          annotations:
            original-image: "{{ request.object.spec.containers[0].image }}"
            source-pod: "{{ request.object.metadata.name }}"
            source-namespace: "{{ request.namespace }}"
            created-at: "{{ time_now() }}"
        spec:
          backoffLimit: 3
          ttlSecondsAfterFinished: 300
          template:
            metadata:
              labels:
                generated-by: unique-job-per-image-policy
            spec:
              restartPolicy: Never
              containers:
              - name: image-processor
                image: busybox:1.35
                command: ["/bin/sh"]
                args:
                - -c
                - |
                  echo "Processing image: {{ request.object.spec.containers[0].image }}"
                  echo "Source pod: {{ request.object.metadata.name }}"
                  echo "Namespace: {{ request.namespace }}"
                  echo "Job name: img-{{ base64_encode(request.object.spec.containers[0].image) | truncate(@, `8`) | replace_all(@, '+', 'x') | replace_all(@, '/', 'y') | replace_all(@, '=', 'z') | lower(@) }}"
                  echo "This job is unique per image - multiple pods with same image will not create duplicate jobs"
                env:
                - name: ORIGINAL_IMAGE
                  value: "{{ request.object.spec.containers[0].image }}"
                - name: SOURCE_POD
                  value: "{{ request.object.metadata.name }}"
                - name: SOURCE_NAMESPACE
                  value: "{{ request.namespace }}"