namespace: servicenow
instanceName: "your-instance"
clusterName: "your-cluster"

image:
  repository: docker.io/servicenowdocker/informer
  tag: 2.3.0
  pullPolicy: Always

serviceNow:
  instanceUrl: "https://your-instance.service-now.com"
  acceptEula: "N"

resources:
  limits:
    cpu: 100m
  requests:
    cpu: 20m
    memory: 200Mi

nodeSelector:
  kubernetes.azure.com/scalesetpriority: system

tolerations:
  - key: CriticalAddonsOnly
    operator: Exists
    effect: NoSchedule
  - key: node.kubernetes.io/not-ready
    operator: Exists
    effect: NoExecute
  - key: node.kubernetes.io/unreachable
    operator: Exists
    effect: NoExecute

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.azure.com/scalesetpriority
              operator: In
              values:
                - system
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - k8s_informer
          topologyKey: kubernetes.io/hostname

config:
  resyncMin: 0
  sendIntervalSec: 10
  maxCiInMessage: 50
  refreshTimeMin: 0
  fullDiscoveryMin: 1440
  readCommandSec: 60
  heartbeatMin: 5
  maxQueueSizeBytes: 262144000
  maxRetry: 5
  maxEccPayloadSizeBytes: 1048576
  continuousDiscovery: true
  eccSenderIntervalSec: 30
  verboseLogging: false
  skipTlsCertValidation: false
  suppressFrequentChanges: true
  suppressChangesRatePerMin: 0.15
  openshift: false
  addNodeLabels: true
  createServerCi: true
  getClusterVersion: true
  getResourceMaxBytes: 5242880
  maxGetResourceRequests: 10
  httpRestApiPostRetryCount: 2
  maxElapsedTimeMs: 10000
  selfPatchingAllowed: true 