apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: mutate-image-registry
  annotations:
    policies.kyverno.io/title: Mutate Image Registry
    pod-policies.kyverno.io/autogen-controllers: none
    policies.kyverno.io/category: Sample
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      This policy mutates Pod image references to use the specified Azure Container Registry
      and injects the necessary image pull secrets.
spec:
  background: false
  rules:
    - name: mutate-container-images
      match:
        any:
        - resources:
            kinds:
            - Pod
      exclude:
        any:
        - resources:
            selector:
              matchLabels:
                skip-verify: "true"
      mutate:
        foreach:
        - list: "request.object.spec.containers"
          patchStrategicMerge:
            spec:
              containers:
              - name: "{{ element.name }}"
                image: "{{ regex_replace_all('^(localhost/|(?:[a-z0-9]+\\.)+[a-z0-9]+/)?(.*)$', element.image, 'crdevcr.azurecr.io/$2') }}"
              imagePullSecrets:
              - name: "acr-secret"
    - name: mutate-init-container-images
      match:
        any:
        - resources:
            kinds:
            - Pod
      exclude:
        any:
        - resources:
            selector:
              matchLabels:
                skip-verify: "true"
      preconditions:
        all:
        - key: "{{ request.object.spec.initContainers[] || `[]` | length(@) }}"
          operator: GreaterThanOrEquals
          value: 1
      mutate:
        foreach:
        - list: "request.object.spec.initContainers"
          patchStrategicMerge:
            spec:
              initContainers:
              - name: "{{ element.name }}"
                image: "{{ regex_replace_all('^(localhost/|(?:[a-z0-9]+\\.)+[a-z0-9]+/)?(.*)$', element.image, 'crdevcr.azurecr.io/$2') }}" 