apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpu-workload
spec:
  template:
    spec:
      # 1. Add toleration for GPU nodes
      tolerations:
      - key: "nvidia.com/gpu"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
      
      # 2. Add node affinity for GPU nodes
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-type
                operator: In
                values: ["gpu"]
      
      containers:
      - name: gpu-container
        image: your-gpu-image:tag
        # 3. Request GPU resources
        resources:
          limits:
            nvidia.com/gpu: "1"  # Request 1 GPU
          requests:
            nvidia.com/gpu: "1"
            cpu: "4"
            memory: "16Gi"
        # 4. Optional: Add GPU-specific environment variables
        env:
        - name: NVIDIA_VISIBLE_DEVICES
          value: "all"
        - name: NVIDIA_DRIVER_CAPABILITIES
          value: "compute,utility"