apiVersion: apps/v1
kind: Deployment
metadata:
  name: your-infra-workload
spec:
  template:
    spec:
      # 1. Add toleration for the infrastructure taint
      tolerations:
      - key: "workload-type"
        operator: "Equal"
        value: "infrastructure"
        effect: "NoSchedule"
      
      # 2. Add node affinity for infrastructure nodes
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-type
                operator: In
                values: ["infrastructure"]
          # Optional: prefer D-series v3 VMs
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
              - key: "karpenter.azure.com/sku-family"
                operator: In
                values: ["D"]
              - key: "karpenter.azure.com/sku-version"
                operator: In
                values: ["3"]
      
      containers:
      - name: your-infra-container
        image: your-image:tag
        # Add appropriate resources for infrastructure workloads
        resources:
          requests:
            cpu: "500m"
            memory: "1Gi"
          limits:
            cpu: "2"
            memory: "4Gi"