apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: route-infra-workloads
  annotations:
    policies.kyverno.io/title: Route Infrastructure Workloads
    policies.kyverno.io/category: Workload Distribution
    policies.kyverno.io/subject: Deployment
    policies.kyverno.io/description: >-
      This policy adds node affinity and tolerations to route infrastructure workloads
      to infrastructure nodes based on namespace labels.
spec:
  validationFailureAction: audit
  rules:
    - name: route-infra-workloads
      match:
        any:
        - resources:
            kinds:
              - Deployment
            namespaceSelector:
              matchExpressions:
                - key: workload-type
                  operator: In
                  values:
                    - infrastructure
      mutate:
        patchStrategicMerge:
          spec:
            template:
              spec:
                +(tolerations):
                  - key: "workload-type"
                    operator: "Equal"
                    value: "infrastructure"
                    effect: "NoSchedule"
                +(affinity):
                  nodeAffinity:
                    requiredDuringSchedulingIgnoredDuringExecution:
                      nodeSelectorTerms:
                      - matchExpressions:
                        - key: node-type
                          operator: In
                          values:
                            - infrastructure
                  podAntiAffinity:
                    preferredDuringSchedulingIgnoredDuringExecution:
                    - weight: 100
                      podAffinityTerm:
                        labelSelector:
                          matchExpressions:
                          - key: app
                            operator: In
                            values:
                            - "{{ request.object.spec.template.metadata.labels.app }}"
                        topologyKey: kubernetes.io/hostname
                +(topologySpreadConstraints):
                  - maxSkew: 1
                    topologyKey: topology.kubernetes.io/zone
                    whenUnsatisfied: DoNotSchedule
                    labelSelector:
                      matchLabels:
                        app: "{{ request.object.spec.template.metadata.labels.app }}" 