apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: route-high-perf-workloads
  annotations:
    policies.kyverno.io/title: Route High Performance Workloads
    policies.kyverno.io/category: Workload Distribution
    policies.kyverno.io/subject: Deployment
    policies.kyverno.io/description: >-
      This policy adds node affinity and tolerations to route high performance workloads
      to compute-optimized nodes based on namespace labels.
spec:
  validationFailureAction: audit
  rules:
    - name: route-high-perf-workloads
      match:
        any:
        - resources:
            kinds:
              - Deployment
            namespaceSelector:
              matchExpressions:
                - key: workload-type
                  operator: In
                  values:
                    - high-performance
      preconditions:
        all:
        - key: "{{ request.object.spec.template.metadata.labels.app || '' }}"
          operator: NotEquals
          value: ""
      mutate:
        patchStrategicMerge:
          spec:
            template:
              spec:
                +(tolerations):
                  - key: "workload-type"
                    operator: "Equal"
                    value: "high-performance"
                    effect: "NoSchedule"
                +(affinity):
                  nodeAffinity:
                    requiredDuringSchedulingIgnoredDuringExecution:
                      nodeSelectorTerms:
                      - matchExpressions:
                        - key: node-type
                          operator: In
                          values:
                            - high-performance
                  podAntiAffinity:
                    preferredDuringSchedulingIgnoredDuringExecution:
                    - weight: 100
                      podAffinityTerm:
                        labelSelector:
                          matchExpressions:
                          - key: app
                            operator: In
                            values:
                            - "{{ request.object.spec.template.metadata.labels.app }}"
                        topologyKey: kubernetes.io/hostname 