apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}-test-bad
  namespace: {{ .Release.Namespace }}
  labels:
    helm.sh/test: resource-limits
  annotations:
    helm.sh/hook: test
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
spec:
  serviceAccountName: {{ .Release.Name }}-test-sa
  containers:
  - name: test
    image: bitnami/kubectl:latest
    command: 
    - /bin/sh
    - -c
    - |
      if kubectl apply -f - <<EOF
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: test-bad
        namespace: {{ .Release.Namespace }}
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: test-bad
        template:
          metadata:
            labels:
              app: test-bad
          spec:
            containers:
            - name: nginx
              image: nginx
      EOF
      then
        echo "Policy violation not detected"
        exit 1
      else
        echo "Policy violation correctly detected"
        exit 0
      fi
  restartPolicy: Never 