apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-test-istio-label
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook: test-success
    helm.sh/hook-weight: "-5"
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-test-istio-label
  annotations:
    helm.sh/hook: test-success
    helm.sh/hook-weight: "-4"
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-test-istio-label
  annotations:
    helm.sh/hook: test-success
    helm.sh/hook-weight: "-3"
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-test-istio-label
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-test-istio-label
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Release.Name }}-test-istio-label
  annotations:
    helm.sh/hook: test-success
    helm.sh/hook-weight: "-2"
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
  labels:
    istio.io/rev: asm-1-22  # This should be mutated to asm-1-23
---
apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}-test-istio-label
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook: test-success
    helm.sh/hook-weight: "-1"
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
spec:
  serviceAccountName: {{ .Release.Name }}-test-istio-label
  containers:
  - name: test
    image: bitnami/kubectl:latest
    command:
    - /bin/bash
    - -c
    - |
      # Wait for policy to be ready
      sleep 10
      
      # Check if the namespace was created and label was mutated
      NS_LABEL=$(kubectl get ns {{ .Release.Name }}-test-istio-label -o jsonpath='{.metadata.labels.istio\.io/rev}')
      if [ "$NS_LABEL" != "asm-1-23" ]; then
        echo "Expected istio.io/rev label to be asm-1-23, but got $NS_LABEL"
        exit 1
      fi
      echo "✅ Namespace label was correctly mutated to asm-1-23"
      
      # Clean up the test namespace
      kubectl delete ns {{ .Release.Name }}-test-istio-label
  restartPolicy: Never 