apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: app-gitrepo
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/mycompany/app-charts.git
  ref:
    branch: main
  secretRef:
    name: git-credentials 