apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kyverno
  namespace: apps
spec:
  interval: 5m
  # No dependencies - can run in parallel with other tiers
  chart:
    spec:
      chart: ./master-chart
      sourceRef:
        kind: GitRepository
        name: app-gitrepo
        namespace: flux-system
      interval: 1m
  timeout: 5m
  install:
    remediation:
      retries: 3
    # Explicitly handle CRDs
    crds: CreateReplace
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
    cleanupOnFail: true
    # Explicitly handle CRDs during upgrades
    crds: CreateReplace
  # Only enable Kyverno components
  values:
    global:
      environment: production
      clusterDomain: cluster.local
      imageRegistry: acr.io/mycompany
      imagePullSecrets:
        - name: acr-secret
      # Enable automatic CRD installation
      autoInstallCRDs: true
    
    # Disable all application tiers
    database:
      enabled: false
    cache:
      enabled: false
    api:
      enabled: false
    frontend:
      enabled: false
    monitoring:
      enabled: false
    
    # Enable Kyverno
    kyverno:
      enabled: true
      image:
        repository: ghcr.io/kyverno/kyverno
        tag: v1.10.0
      resources:
        requests:
          memory: 512Mi
          cpu: 250m
        limits:
          memory: 1Gi
          cpu: 500m 