apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tier2-cache
  namespace: apps
spec:
  interval: 5m
  # This is the key part - explicitly depend on tier1
  dependsOn:
    - name: tier1-database
  chart:
    spec:
      chart: ./master-chart
      sourceRef:
        kind: GitRepository
        name: app-gitrepo
        namespace: flux-system
      interval: 1m
  timeout: 5m
  install:
    remediation:
      retries: 3
    crds: CreateReplace
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
    cleanupOnFail: true
    crds: CreateReplace
  # Only enable tier2 components
  values:
    global:
      environment: production
      clusterDomain: cluster.local
      imageRegistry: acr.io/mycompany
      imagePullSecrets:
        - name: acr-secret
    
    # Database is already deployed by tier1
    database:
      enabled: false
    
    # Enable cache
    cache:
      enabled: true
    
    # Disable higher tier components
    api:
      enabled: false
    frontend:
      enabled: false
    monitoring:
      enabled: false 