apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tier1-database
  namespace: apps
spec:
  interval: 5m
  chart:
    spec:
      chart: ./master-chart
      sourceRef:
        kind: GitRepository
        name: app-gitrepo
        namespace: flux-system
      interval: 1m
  # Increase timeout to allow for resources to be ready
  timeout: 5m
  install:
    remediation:
      retries: 3
    # Explicitly handle CRDs
    crds: CreateReplace
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
    cleanupOnFail: true
    # Explicitly handle CRDs during upgrades
    crds: CreateReplace
  # Only enable tier1 components
  values:
    global:
      environment: production
      clusterDomain: cluster.local
      imageRegistry: acr.io/mycompany
      imagePullSecrets:
        - name: acr-secret
      # Enable automatic CRD installation
      autoInstallCRDs: true
      # Global CRDs that are required for all components
      requiredCRDs:
        - "ingressroutes.traefik.containo.us"
        - "middlewares.traefik.containo.us"
    
    # Only enable database
    database:
      enabled: true
      # Database doesn't require any CRDs
      requiresCRDs: false
      requiredCRDs: []
    
    # Disable other components
    cache:
      enabled: false
    api:
      enabled: false
    frontend:
      enabled: false
    monitoring:
      enabled: false 