apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: simple-string-policy
spec:
  background: false
  rules:
    - name: test-string-comparison
      match:
        any:
        - resources:
            kinds:
            - Pod
      preconditions:
        all:
        - key: request.object.spec.containers[0].image
          operator: StartsWith
          value: container-registry.xxx.net/
      generate:
        apiVersion: batch/v1
        kind: Job
        name: "string-test-job-{{ request.object.metadata.name }}"
        namespace: "{{request.namespace}}"
        synchronize: false
        data:
          apiVersion: batch/v1
          kind: Job
          metadata:
            name: "string-test-job-{{ request.object.metadata.name }}"
          spec:
            template:
              spec:
                containers:
                - name: test-container
                  image: busybox
                  command: ["echo", "String test job running for {{ request.object.spec.containers[0].image }}"]
                restartPolicy: Never
            backoffLimit: 1 