apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: prevent-duplicate-hostnames
spec:
  validationFailureAction: enforce
  rules:
  - name: check-hostname-uniqueness
    match:
      resources:
        kinds:
        - VirtualService
    validate:
      message: "VirtualServices must have unique hostnames"
      pattern:
        spec:
          hosts: "?*" 