apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: prevent-duplicate-hostnames
  annotations:
    policies.kyverno.io/title: Prevent Duplicate Hostnames
    policies.kyverno.io/category: Networking
    policies.kyverno.io/severity: high
    policies.kyverno.io/subject: VirtualService
    policies.kyverno.io/description: >-
      This policy prevents VirtualServices from using hostnames that are already in use,
      which could lead to conflicts.
spec:
  validationFailureAction: Enforce
  background: true
  rules:
  - name: check-hostname-uniqueness
    match:
      resources:
        kinds:
        - VirtualService
    context:
    - name: existingVirtualServices
      apiCall:
        urlPath: "/apis/networking.istio.io/v1/virtualservices"
        jmesPath: "items"
    preconditions:
      all:
      - key: "{{ request.object.spec.hosts | length(@) }}"
        operator: GreaterThan
        value: 0
    validate:
      message: "Hostname already in use by another VirtualService"
      deny:
        conditions:
          any:
          - key: "{{ existingVirtualServices[?metadata.name != '{{ request.object.metadata.name }}'].spec.hosts[0] }}"
            operator: Contains
            value: "{{ request.object.spec.hosts[0] }}" 