apiVersion: v1
kind: ServiceAccount
metadata:
  name: kyverno-admin
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kyverno-policy-admin
rules:
# For policy reports
- apiGroups: ["wgpolicyk8s.io"]
  resources: ["policyreports", "clusterpolicyreports"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

# For namespace operations
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["create", "delete", "get", "list", "watch", "update", "patch"]

# For deployment operations
- apiGroups: ["apps"]
  resources: ["deployments", "statefulsets", "daemonsets", "replicasets"]
  verbs: ["create", "delete", "get", "list", "watch", "update", "patch"]

# For pod operations
- apiGroups: [""]
  resources: ["pods", "pods/log", "pods/status", "pods/exec"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

# For Kyverno policies
- apiGroups: ["kyverno.io"]
  resources: ["clusterpolicies", "policies", "policyexceptions", "clusterreports", "reports"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

# For job operations
- apiGroups: ["batch"]
  resources: ["jobs", "cronjobs"]
  verbs: ["get", "list", "watch", "create", "delete", "update", "patch"]

# For secrets and configmaps
- apiGroups: [""]
  resources: ["secrets", "configmaps"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

# For service operations
- apiGroups: [""]
  resources: ["services", "endpoints"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

# For events
- apiGroups: [""]
  resources: ["events"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]

# For image verification
- apiGroups: [""]
  resources: ["imagerepositories"]
  verbs: ["get", "list", "watch"]

# For admission reviews
- apiGroups: ["admission.k8s.io"]
  resources: ["validatingwebhookconfigurations", "mutatingwebhookconfigurations"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

# For networking
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses", "networkpolicies"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

# For RBAC operations
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["roles", "rolebindings", "clusterroles", "clusterrolebindings"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kyverno-policy-admin
subjects:
- kind: ServiceAccount
  name: kyverno-admin
  namespace: default
roleRef:
  kind: ClusterRole
  name: kyverno-policy-admin
  apiGroup: rbac.authorization.k8s.io