apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: replace-image-registry
  annotations:
    policies.kyverno.io/title: Replace Image Registry
    pod-policies.kyverno.io/autogen-controllers: none
    policies.kyverno.io/category: Sample
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
    kyverno.io/kyverno-version: 1.7.2
    policies.kyverno.io/minversion: 1.6.0
    kyverno.io/kubernetes-version: "1.23"
    policies.kyverno.io/description: >-
      This policy mutates Pod image references to use the specified Azure Container Registry,
      validates image existence in ACR, and generates jobs to push missing images.
spec:
  background: false
  rules:
    - name: verify-images
      match:
        any:
        - resources:
            kinds:
            - Pod
      exclude:
        any:
        - resources:
            selector:
              matchLabels:
                skip-verify: "true"
      verifyImages:
      - imageReferences:
        - "*"
        repository: crdevcr.azurecr.io
        required: false
        mutateDigest: false
    - name: generate-push-job
      match:
        any:
        - resources:
            kinds:
            - Pod
      exclude:
        any:
        - resources:
            selector:
              matchLabels:
                skip-verify: "true"
      preconditions:
        all:
        - key: "{{ images.verified.*.verified || `false` }}"
          operator: Equals
          value: false
      generate:
apiVersion: batch/v1
kind: Job
metadata:
  name: test-acr-push-nginx
  labels:
    skip-verify: "true"
spec:
  template:
    metadata:
      labels:
        skip-verify: "true"
    spec:
      containers:
      - name: push-image
        image: mcr.microsoft.com/azure-cli
        env:
        - name: AZURE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: acr-auth
              key: client-id
        - name: AZURE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: acr-auth
              key: client-secret
        - name: AZURE_TENANT_ID
          valueFrom:
            secretKeyRef:
              name: acr-auth
              key: tenant-id
        command:
        - /bin/bash
        - -c
        - |
          set -e
          echo "Starting image import process..."
          
          # Login to Azure using service principal
          echo "Logging in to Azure..."
          az login --service-principal \
            --username $AZURE_CLIENT_ID \
            --password $AZURE_CLIENT_SECRET \
            --tenant $AZURE_TENANT_ID
          
          echo "Setting subscription..."
          az account set -s 133d5755-4074-4d6e-ad38-eb2a6ad12903
          
          echo "Current subscription:"
          az account show
          
          echo "Listing available ACRs:"
          az acr list --query "[].{name:name,resourceGroup:resourceGroup}" -o table
          
          echo "Checking ACR access..."
          az acr show --name crdevacr2 --resource-group dev-rg
          
          # Import the image directly to ACR
          echo "Importing nginx image to ACR..."
          az acr import \
            --name crdevacr2 \
            --source docker.io/library/nginx:latest \
            --image nginx:latest
          
          echo "Process complete"
      restartPolicy: Never
  backoffLimit: 3 
    - name: mutate-container-images
      match:
        any:
        - resources:
            kinds:
            - Pod
      exclude:
        any:
        - resources:
            selector:
              matchLabels:
                skip-verify: "true"
      preconditions:
        all:
        - key: "{{ images.verified.*.verified || `false` }}"
          operator: AnyIn
          value: 
          - true
          - false
      mutate:
        foreach:
        - list: "request.object.spec.containers"
          patchStrategicMerge:
            spec:
              containers:
              - name: "{{ element.name }}"
                image: "{{ regex_replace_all('^(localhost/|(?:[a-z0-9]+\\.)+[a-z0-9]+/)?(.*)$', element.image, 'crdevcr.azurecr.io/$2') }}"
              imagePullSecrets:
              - name: "acr-secret"
    - name: mutate-init-container-images
      match:
        any:
        - resources:
            kinds:
            - Pod
      exclude:
        any:
        - resources:
            selector:
              matchLabels:
                skip-verify: "true"
      preconditions:
        all:
        - key: "{{ request.object.spec.initContainers[] || `[]` | length(@) }}"
          operator: GreaterThanOrEquals
          value: 1
      mutate:
        foreach:
        - list: "request.object.spec.initContainers"
          patchStrategicMerge:
            spec:
              initContainers:
              - name: "{{ element.name }}"
                image: "{{ regex_replace_all('^(localhost/|(?:[a-z0-9]+\\.)+[a-z0-9]+/)?(.*)$', element.image, 'crdevcr.azurecr.io/$2') }}" 