apiVersion: batch/v1
kind: Job
metadata:
  name: test-acr-push-nginx
  labels:
    skip-verify: "true"
spec:
  template:
    metadata:
      labels:
        skip-verify: "true"
    spec:
      containers:
      - name: push-image
        image: mcr.microsoft.com/azure-cli
        env:
        - name: AZURE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: acr-auth
              key: client-id
        - name: AZURE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: acr-auth
              key: client-secret
        - name: AZURE_TENANT_ID
          valueFrom:
            secretKeyRef:
              name: acr-auth
              key: tenant-id
        command:
        - /bin/bash
        - -c
        - |
          set -e
          echo "Starting image import process..."
          
          # Install necessary tools
          echo "Installing diagnostic tools..."
          apt-get update && apt-get install -y dnsutils curl
          
          # DNS verification
          echo "Verifying DNS resolution..."
          nslookup crdevcr.azurecr.io
          
          # Login to Azure using service principal
          echo "Logging in to Azure..."
          az login --service-principal \
            --username $AZURE_CLIENT_ID \
            --password $AZURE_CLIENT_SECRET \
            --tenant $AZURE_TENANT_ID
          
          echo "Setting subscription..."
          az account set -s 133d5755-4074-4d6e-ad38-eb2a6ad12903
          
          echo "Current subscription:"
          az account show
          
          echo "Listing available ACRs:"
          az acr list --query "[].{name:name,loginServer:loginServer,resourceGroup:resourceGroup}" -o table
          
          echo "Checking ACR access..."
          az acr show --name crdevcr --resource-group dev-rg
          
          # Test ACR connectivity
          echo "Testing ACR connectivity..."
          az acr login --name crdevcr
          
          # Import the image directly to ACR
          echo "Importing nginx image to ACR..."
          az acr import \
            --name crdevcr \
            --source docker.io/library/nginx:latest \
            --image nginx:latest
          
          echo "Process complete"
      restartPolicy: Never
  backoffLimit: 3 
