apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: route-core-workloads
  annotations:
    policies.kyverno.io/title: Route Core Kubernetes Workloads
    policies.kyverno.io/category: Workload Distribution
    policies.kyverno.io/subject: Deployment
    policies.kyverno.io/description: >-
      This policy adds node affinity, tolerations, and topology spread constraints to route
      core Kubernetes workloads (cert-manager, external-secrets, kyverno, etc.) to dedicated
      kubernetes-core nodes with high availability.
spec:
  validationFailureAction: audit
  background: true
  rules:
    - name: route-core-workloads
      match:
        any:
        - resources:
            kinds:
              - Deployment
            namespaceSelector:
              matchExpressions:
                - key: workload-type
                  operator: In
                  values:
                    - kubernetes-core
            selector:
              matchLabels:
                app.kubernetes.io/instance: uk8s-core
      preconditions:
        all:
        - key: "{{ request.object.spec.template.metadata.labels.app || '' }}"
          operator: NotEquals
          value: ""
      mutate:
        patchStrategicMerge:
          spec:
            template:
              spec:
                +(tolerations):
                  - key: "workload-type"
                    operator: "Equal"
                    value: "kubernetes-core"
                    effect: "NoSchedule"
                +(affinity):
                  nodeAffinity:
                    requiredDuringSchedulingIgnoredDuringExecution:
                      nodeSelectorTerms:
                      - matchExpressions:
                        - key: node-type
                          operator: In
                          values:
                            - kubernetes-core
                  podAntiAffinity:
                    preferredDuringSchedulingIgnoredDuringExecution:
                    - weight: 100
                      podAffinityTerm:
                        labelSelector:
                          matchExpressions:
                          - key: app
                            operator: In
                            values:
                            - "{{ request.object.spec.template.metadata.labels.app }}"
                        topologyKey: azure.microsoft.com/hostname
                +(topologySpreadConstraints):
                  - maxSkew: 1
                    topologyKey: azure.microsoft.com/zone
                    whenUnsatisfied: ScheduleAnyway
                    labelSelector:
                      matchLabels:
                        app: "{{ request.object.spec.template.metadata.labels.app }}"
                +(priorityClassName): "system-cluster-critical" 