apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: at12345-dev
  labels:
    app: test-app
    app.kubernetes.io/name: test-pod
  annotations:
    policy-test: "expecting-spot-affinity"
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80 