apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: ${policy.name}
spec:
  validationFailureAction: ${validation.action}
  background: true
  rules:
    - name: ${rule.name}
      match:
        resources:
          kinds:
            - ${resource.kind} 