apiVersion: v1
data:
  ADDONS_KEYVAULT_ROTATION_INTERVAL: 2m
  ADDONS_MONITORING_WORKSPACE_ID: /subscriptions/sub-id/resourceGroups/rg-monitoring-dev/providers/Microsoft.OperationalInsights/workspaces/law-aks-dev
  ADMIN_GROUP_ID: your-admin-group-id
  AUTO_UPGRADE_CHANNEL: patch
  AUTO_UPGRADE_NODE_OS_CHANNEL: SecurityPatch
  CLUSTER_NAME: dev-aks-01
  K8S_VERSION: 1.28.3
  LOCATION: eastus2
  NETWORK_DNS_SERVICE_IP: 172.16.0.10
  NETWORK_POD_CIDR: 10.244.0.0/16
  NETWORK_SERVICE_CIDR: 172.16.0.0/16
  RESOURCE_GROUP: rg-aks-dev
  SYSTEM_NODEPOOL_COUNT: "1"
  SYSTEM_NODEPOOL_MAX_COUNT: "2"
  SYSTEM_NODEPOOL_MAX_PODS: "30"
  SYSTEM_NODEPOOL_MIN_COUNT: "1"
  SYSTEM_NODEPOOL_VM_SIZE: Standard_D4s_v3
  USER_ASSIGNED_IDENTITY_NAME: dev-aks-identity
  USER_NODEPOOL_COUNT: "1"
  USER_NODEPOOL_MAX_COUNT: "3"
  USER_NODEPOOL_MAX_PODS: "30"
  USER_NODEPOOL_MIN_COUNT: "1"
  USER_NODEPOOL_VM_SIZE: Standard_D4s_v3
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/managed-by: azure-service-operator
    environment: development
  name: dev-cluster-config
  namespace: azureserviceoperator-system
---
apiVersion: containerservice.azure.com/v1api20240901
kind: ManagedCluster
metadata:
  labels:
    app.kubernetes.io/managed-by: azure-service-operator
    environment: development
  name: dev-aks-01
  namespace: azureserviceoperator-system
spec:
  aadProfile:
    adminGroupObjectIDs:
    - placeholder-admin-group
    enableAzureRBAC: true
    managed: true
  addonProfiles:
    azureKeyvaultSecretsProvider:
      config:
        enableSecretRotation: false
        rotationPollInterval: 2m
      enabled: true
    azurepolicy:
      enabled: false
    omsagent:
      config:
        logAnalyticsWorkspaceResourceID: /subscriptions/sub-id/resourceGroups/rg-monitoring-dev/providers/Microsoft.OperationalInsights/workspaces/law-aks-dev
      enabled: false
  agentPoolProfiles:
  - availabilityZones:
    - "1"
    count: 1
    enableAutoScaling: true
    maxCount: 2
    maxPods: 30
    minCount: 1
    mode: System
    name: sysnpl1
    nodeTaints:
    - CriticalAddonsOnly=true:NoSchedule
    osDiskSizeGB: 128
    osDiskType: Managed
    osSKU: Ubuntu
    osType: Linux
    vmSize: Standard_D4s_v3
  - availabilityZones:
    - "1"
    count: 1
    enableAutoScaling: true
    maxCount: 3
    maxPods: 30
    minCount: 1
    mode: User
    name: usrnpl1
    nodeLabels:
      kubernetes.azure.com/scalesetpriority: spot
    nodeTaints:
    - kubernetes.azure.com/scalesetpriority=spot:NoSchedule
    osDiskSizeGB: 128
    osDiskType: Managed
    osSKU: Ubuntu
    osType: Linux
    vmSize: Standard_D4s_v3
  apiServerAccessProfile:
    enablePrivateCluster: true
    enablePrivateClusterPublicFQDN: true
  autoUpgradeProfile:
    nodeOSUpgradeChannel: SecurityPatch
    upgradeChannel: patch
  disableLocalAccounts: true
  dnsPrefix: dev-aks-01
  enableRBAC: true
  kubernetesVersion: 1.28.3
  location: eastus2
  networkProfile:
    dnsServiceIP: 172.16.0.10
    ipFamilies:
    - IPv4
    loadBalancerSku: standard
    networkDataplane: cilium
    networkPlugin: azure
    networkPluginMode: overlay
    networkPolicy: cilium
    podCidr: 10.244.0.0/16
    serviceCidr: 172.16.0.0/16
  owner:
    name: rg-aks-dev
  securityProfile:
    defender:
      securityMonitoring:
        enabled: false
    workloadIdentity:
      enabled: true
